### ISSUE TITLE
Publish date question

### ISSUE THREAD

**Issue by kruk1001** [tao-software/tao-schedule-update#7]
Hello, thank you for providing a much needed tool to the WordPress world. My minor challenge is that I created a scheduled update to a page and then set the publish date to be just a few minutes later (so I could see how it worked). It defaulted to 5 hours later for the publish time. Is that by default? Is there a way to override that if I want an update to publish sooner than the default time?

Thanks again!!!

**Comment by Syberspace** [comment]
Hi,
the default should be set to 5 minutes in the future. Less than 5 minutes is not possible.
Have you set the correct timezone under Settings -> General?

**Comment by rlhoward** [comment]
@Syberspace Having a similar issue. I selected the "Scheduled Update" link for the page I wanted to update. Then I made modifications to that page and selected a time 10 minutes in the future in order to test. 
Problem #1: mysteriously, my WordPress dashboard showed a time 19 minutes in the future as the scheduled time for the update, rather than the 10 minutes I selected.
Problem #2: even when the time shown in the dashboard passed, the updates did not go live.

Yes, I verified that the time zone and time for the site are updating accurately. Chron jobs are active. Only other plugins I have working on site in question are Contact Form 7, Yoast SEO, Juiz Last Tweet Widget (which does update with no problem when I have a new Tweet). I am using the Enfold theme for this particular website and WordPress 4.5.3; is there a know incompatibility with that theme and/or version of WordPress?

The only way I can see the scheduled update is to go in to the dashboard and click "Publish Now" on the scheduled update. This totally defeats the purpose for which I installed the plugin, which was so I could do updates to existing pages and have those go live at midnight, while I enjoy a good night's sleep.

Is there some other step I need to take in order for updates to occur as scheduled? What am I missing here?

**Comment by chriskruse** [comment]
The issue appears to be related to how you are calculating and setting the timestamp for the cron. Even with the correct timezone setting, it is off. According the the WP docs for `wp schedule single event()`, it expects the timestamp to be in UTC time, not local.

**Comment by Syberspace** [comment]
Thanks for spotting this bug @sumbudy. 
We'll fix it in the next release

**Comment by rlhoward** [comment]
@sumbudy - thanks; I will change time zone to UTC format and retest!

**Comment by happymanuk** [comment]
I've just taken over a website that is running this plug-in and most of the time it works great.  I've experienced this issue a couple of times where the update doesn't go live, and I have to click on 'Publish Now'.  Is there any update that fixes this bug ?

Thanks in advance

**Comment by Syberspace** [comment]
I am pretty sure one of the updates we've done over the last year has fixed this problem. If not, please feel free to open another issue.
